fn main() {
    // No native build script is required. The crate is consumed as a plain
    // cdylib/rlib; FFI scaffolding is generated by UniFFI at compile time via
    // the #[uniffi::export] proc macros in lib.rs / android.rs.
}
