package com.telebox.app.ui.theme

import androidx.compose.ui.graphics.Color

/*
 * TeleBox "Onyx" palette.
 *
 * A dark, dramatic, monochrome design language. The accent is deliberately
 * monochrome (near-white on near-black) rather than a chromatic brand hue, so
 * the interface reads as polished onyx glass. Semantic colors (error, success,
 * warning, file types) stay chromatic because they carry meaning, never
 * decoration.
 */

val Seed = Color(0xFF0A0A0C)

val PrimaryLight = Color(0xFF18181B)
val OnPrimaryLight = Color(0xFFFAFAFA)
val PrimaryContainerLight = Color(0xFFE4E4E7)
val OnPrimaryContainerLight = Color(0xFF18181B)
val SecondaryLight = Color(0xFF3F3F46)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFE4E4E7)
val OnSecondaryContainerLight = Color(0xFF18181B)
val TertiaryLight = Color(0xFF52525B)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFE4E4E7)
val OnTertiaryContainerLight = Color(0xFF18181B)
val BackgroundLight = Color(0xFFF7F7F8)
val OnBackgroundLight = Color(0xFF09090B)
val SurfaceLight = Color(0xFFF7F7F8)
val OnSurfaceLight = Color(0xFF09090B)
val SurfaceVariantLight = Color(0xFFE4E4E7)
val OnSurfaceVariantLight = Color(0xFF52525B)
val OutlineLight = Color(0xFF71717A)
val OutlineVariantLight = Color(0xFFD4D4D8)
val InverseSurfaceLight = Color(0xFF18181B)
val InverseOnSurfaceLight = Color(0xFFFAFAFA)
val InversePrimaryLight = Color(0xFFFAFAFA)
val SurfaceDimLight = Color(0xFFE7E7E9)
val SurfaceBrightLight = Color(0xFFFFFFFF)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF2F2F3)
val SurfaceContainerLight = Color(0xFFEDEDEF)
val SurfaceContainerHighLight = Color(0xFFE7E7E9)
val SurfaceContainerHighestLight = Color(0xFFE1E1E4)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

val PrimaryDark = Color(0xFFF4F4F5)
val OnPrimaryDark = Color(0xFF0A0A0C)
val PrimaryContainerDark = Color(0xFF1C1C21)
val OnPrimaryContainerDark = Color(0xFFEDEDEF)
val SecondaryDark = Color(0xFFB4B4BC)
val OnSecondaryDark = Color(0xFF0A0A0C)
val SecondaryContainerDark = Color(0xFF1F1F24)
val OnSecondaryContainerDark = Color(0xFFE4E4E7)
val TertiaryDark = Color(0xFF8A8A93)
val OnTertiaryDark = Color(0xFF0A0A0C)
val TertiaryContainerDark = Color(0xFF26262B)
val OnTertiaryContainerDark = Color(0xFFE4E4E7)
val BackgroundDark = Color(0xFF050506)
val OnBackgroundDark = Color(0xFFEDEDEF)
val SurfaceDark = Color(0xFF050506)
val OnSurfaceDark = Color(0xFFEDEDEF)
val SurfaceVariantDark = Color(0xFF1F1F24)
val OnSurfaceVariantDark = Color(0xFFA1A1AA)
val OutlineDark = Color(0xFF3F3F46)
val OutlineVariantDark = Color(0xFF27272A)
val InverseSurfaceDark = Color(0xFFEDEDEF)
val InverseOnSurfaceDark = Color(0xFF18181B)
val InversePrimaryDark = Color(0xFF18181B)
val SurfaceDimDark = Color(0xFF050506)
val SurfaceBrightDark = Color(0xFF2A2A30)
val SurfaceContainerLowestDark = Color(0xFF020203)
val SurfaceContainerLowDark = Color(0xFF0A0A0C)
val SurfaceContainerDark = Color(0xFF101013)
val SurfaceContainerHighDark = Color(0xFF17171B)
val SurfaceContainerHighestDark = Color(0xFF1F1F24)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF450A0A)
val ErrorContainerDark = Color(0xFF7A1414)
val OnErrorContainerDark = Color(0xFFFFDAD6)

val Brand = Color(0xFFF4F4F5)
val Success = Color(0xFF3D8B5F)
val SuccessDark = Color(0xFF79D99A)
val Warning = Color(0xFFC47B16)
val WarningDark = Color(0xFFFFB95F)
val InfoBlue = Color(0xFFC4C4CC)

val FileImage = Color(0xFFC2185B)
val FileImageContainer = Color(0xFFFFD9E3)
val FileVideo = Color(0xFF6A1B9A)
val FileVideoContainer = Color(0xFFF3DAFF)
val FileAudio = Color(0xFF1B7A45)
val FileAudioContainer = Color(0xFFC4F0D0)
val FilePdf = Color(0xFFB3261E)
val FilePdfContainer = Color(0xFFFFDAD6)
val FileDocument = Color(0xFF00668A)
val FileDocumentContainer = Color(0xFFC4E7FF)
val FileText = Color(0xFF4D616D)
val FileTextContainer = Color(0xFFD0E6F3)
val FileSpreadsheet = Color(0xFF1B7A45)
val FileSpreadsheetContainer = Color(0xFFC4F0D0)
val FilePresentation = Color(0xFF9A4500)
val FilePresentationContainer = Color(0xFFFFDCC3)
val FileArchive = Color(0xFF7A5800)
val FileArchiveContainer = Color(0xFFFFDEA3)
val FileCode = Color(0xFF465AA8)
val FileCodeContainer = Color(0xFFDCE1FF)
val FileFolder = Color(0xFF00668A)
val FileFolderContainer = Color(0xFFC4E7FF)
val FileGeneric = Color(0xFF4D616D)
val FileGenericContainer = Color(0xFFD0E6F3)

val FileImageDark = Color(0xFFFFB1C8)
val FileVideoDark = Color(0xFFE3B5FF)
val FileAudioDark = Color(0xFF79D99A)
val FilePdfDark = Color(0xFFFFB4AB)
val FileDocumentDark = Color(0xFFB7C4FF)
val FileTextDark = Color(0xFFC4C4CC)
val FileSpreadsheetDark = Color(0xFF79D99A)
val FilePresentationDark = Color(0xFFFFB77C)
val FileArchiveDark = Color(0xFFFFBA30)
val FileCodeDark = Color(0xFFB7C4FF)
val FileFolderDark = Color(0xFFE4E4E7)
val FileGenericDark = Color(0xFFC4C4CC)

val AuthGradientStartDark = Color(0xFF1C1C21)
val AuthGradientEndDark = Color(0xFF050506)
val AuthGradientStartLight = Color(0xFFE4E4E7)
val AuthGradientEndLight = Color(0xFFF7F7F8)

val Danger = Color(0xFFBA1A1A)
val DangerSoft = Color(0x1ABA1A1A)
val ConfirmSurface = Color(0xFF17171B)
